# config/agents_config_example.yaml
agents:
  - name: WebBrowsingAgent
    type: web_browsing
    params:
      api_key: "${GROQ_API_KEY}"
      search_api_key: "${GOOGLE_API_KEY}"
      search_engine_id: "${GOOGLE_CX}"

  - name: DataProcessingAgent1
    type: data_processing
    params: {}

  - name: ReportingAgent1
    type: reporting
    params: {}
